basePath: /
definitions:
  main.projeto:
    properties:
      Description:
        type: string
      equipe:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /projetos/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.projeto'
            type: array
      summary: Get All Projects
  /projetos/{id}:
    get:
      parameters:
      - description: Projeto ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.projeto'
      summary: Get Projeto By ID
swagger: "2.0"
